In [2]:
#######################################################
# Created-Date: 04/15/2016                            #
# Last Modified: 04/27/2016                           #
# Created by: Avineesh Vasudevan , Shravan Kumar ,    #
#             Asish Mahapatra                         #
#                                                     #
# Objective: Build models to predict the song hit rate#
#            based on KNN and Trees classifier models #
#                                                     #
#                                                     #
# Instruction before running:                         #
# 1. Please change the file path of directory         # 
# 2. change ranges based on the number of lyrics      # 
#    you have in the directory                        #  
# 3. Please follow similar nomenclature as used in the# 
#    code                                             #
# 4. Please use the array list of only the years      #
#    under consideration and comment the rest         #
# 5. Please use the scenario definition to assign 0's #
#    to the relevant subset of the super set          #
#######################################################

# Importing required libraries
import pandas as pd
import matplotlib.pyplot as plt
import pandas.io.data
from statsmodels import regression
import math
import statsmodels.api as sm
import datetime
import numpy 
from patsy import dmatrices
from sklearn.cross_validation import train_test_split
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import roc_curve, auc


C:\Users\avinesh\Anaconda3\lib\site-packages\pandas\io\data.py:33: FutureWarning: 
The pandas.io.data module is moved to a separate package (pandas-datareader) and will be removed from pandas in a future version.
After installing the pandas-datareader package (https://github.com/pydata/pandas-datareader), you can change the import ``from pandas.io import data, wb`` to ``from pandas_datareader import data, wb``.
  FutureWarning)


In [3]:
# Building and Analyzing Data Scenario 1
dhome = "/Users/avinesh/Google Drive/Courseworks/2 Sem/Python-based Data Analytics/Python Project/All Data/fsongs"
year = ['2030','2020']
# Adding label 1 to 2020 Dataset
filepath = dhome+year[0]+".csv"
df=pd.read_csv(filepath)
grades = []


In [4]:
for row in df['ranks']:
    grades.append(1)
    
df['grades'] = grades


In [5]:
len(df['grades'])

100

In [6]:

# Adding label 0 to 2030 Dataset
filepath = dhome+year[1]+".csv"
df1=pd.read_csv(filepath)
grades = []
for row in df1['ranks']:
    grades.append(0)

df1['grades'] = grades

df = df.append(df1)




In [8]:
# Dropping Duplicates
od = df.sort(['songs','artists'], ascending=[1,0])
ot=od.drop_duplicates(['songs','artists'], keep='first')
print(ot.shape)
ot.pop('ranks')
ot.pop('ids')
ot.pop('artists')
ot.pop('songs')
ot['grades'].value_counts()

(202, 23)


C:\Users\avinesh\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app


0    102
1    100
Name: grades, dtype: int64

In [10]:
# Splitting data into train and test data
from sklearn.cross_validation import train_test_split
df_train,df_test = train_test_split(ot,random_state=0)

print(df_train.shape)
print(df_test.shape)


(151, 19)
(51, 19)
1    78
0    73
Name: grades, dtype: int64
0    29
1    22
Name: grades, dtype: int64


In [11]:
# Logistic Regression Without PCA
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
y = df_train['grades']
df_train.pop('grades')
model_lr = LogisticRegression()
model_lr.fit(df_train, y)  
print(model_lr.score(df_train, y))

0.675496688742


In [12]:
# Predicting Logistic Regression on Testing Dataet
z = df_test['grades']
df_test.pop('grades')
fit = model_lr.predict(df_test)

In [13]:
# Summary Statistics for Logistic Regression
print(metrics.classification_report(fit, z))
print(metrics.accuracy_score(fit, z))     
print(metrics.confusion_matrix(fit, z))

             precision    recall  f1-score   support

          0       0.45      0.54      0.49        24
          1       0.50      0.41      0.45        27

avg / total       0.48      0.47      0.47        51

0.470588235294
[[13 11]
 [16 11]]


In [19]:
model_lr.coef_

array([[  2.09063048e-01,  -3.52035691e-01,   9.10697272e-04,
          1.52334429e+00,   2.28745140e-02,  -2.32349170e-02,
          7.19249664e-02,   8.76410185e-01,  -3.33220700e-01,
         -6.34637320e-03,  -4.19162508e-01,   4.72013593e-01,
         -4.19126147e-03,  -3.70828056e-02,  -1.65969093e-01,
          2.99823665e-01,  -3.29563406e-01,  -1.27682501e-01]])

In [47]:


probs = model_lr.predict_proba(df_test)
print(probs)
print(metrics.roc_auc_score(fit, probs[:, 1]))
print(len(probs))

Area under the ROC curve : 0.500000


In [48]:
# Evaluating the model using cross-validation(using 10-Fold)
md_Y = ot['grades']
ot.pop('grades')
md_X = ot

In [49]:
from sklearn.cross_validation import cross_val_score
scores = cross_val_score(LogisticRegression(), md_X, md_Y, scoring='accuracy', cv=10)
print (scores)
print (scores.mean())

[ 0.79347826  0.79347826  0.79347826  0.79347826  0.79120879  0.8         0.8
  0.8         0.8         0.8       ]
0.796512183469


In [ ]:
df_train,df_test = train_test_split(ot,random_state=0)

print(df_train.shape)
print(df_test.shape)
print(df_train['grades'].value_counts())
print(df_test['grades'].value_counts())

In [ ]:
#implementing trees

In [33]:
# Splitting into independent and dependent variables
ys1, xs1 = dmatrices('grades ~ acousticness + danceability + duration + energy + key + liveness + loudness + mode + speechiness + tempo + time_signature + valence + Anger + Surprise + Love + Joy + Sadness + Fear', 
                   data = ot, return_type="dataframe")
ys1 = numpy.ravel(ys1)


In [37]:
xs1.pop('Intercept')

19    1
13    1
65    1
17    1
87    1
70    1
40    1
62    1
71    1
97    1
8     1
2     1
15    1
80    1
19    1
14    1
84    1
48    1
54    1
55    1
7     1
6     1
35    1
37    1
98    1
55    1
47    1
49    1
64    1
29    1
     ..
77    1
1     1
20    1
46    1
12    1
78    1
11    1
40    1
91    1
96    1
10    1
25    1
26    1
62    1
66    1
82    1
72    1
16    1
74    1
39    1
13    1
8     1
18    1
88    1
83    1
92    1
68    1
6     1
16    1
72    1
Name: Intercept, dtype: float64

In [38]:
xs1

acousticness  danceability   duration    energy  key  liveness  loudness  \
19      0.074356      0.517933  393.60000  0.492540    1  0.069184    -7.396   
13      0.074356      0.517933  393.60000  0.492540    1  0.069184    -7.396   
65      0.473817      0.511773  242.36000  0.823738    9  0.080829    -7.269   
17      0.004035      0.682043  201.77333  0.987871    2  0.283666    -3.859   
87      0.007207      0.784116  306.29288  0.664036    9  0.158843    -8.482   
70      0.068485      0.806061  188.02667  0.855451    9  0.116679    -5.313   
40      0.096857      0.927517  215.33333  0.530833    5  0.160141    -6.520   
62      0.038555      0.657365  184.61333  0.558068    8  0.091263    -7.474   
71      0.165766      0.164260  287.37333  0.724350    7  0.046118    -5.699   
97      0.970227      0.309855   25.05098  0.037436    9  0.111845   -17.672   
8       0.157461      0.772159  196.31020  0.847969    4  0.129609    -9.084   
2       0.205136      0.840790  188.08000  0.836344    4  0.112933    -9.618   
15      0.682217      0.517781  204.04000  0.457250   10  0.105137    -5.470   
80      0.348156      0.631360  273.53333  0.734136    5  0.134955    -7.480   
19      0.283630      0.672349  212.28798  0.709183    1  0.082996    -7.884   
14      0.024585      0.746524  243.28000  0.866535    5  0.154258    -8.525   
84      0.622172      0.423947  216.58331  0.236798    6  0.095008   -13.035   
48      0.003475      0.862859  263.82667  0.611065    7  0.085732    -4.775   
54      0.140373      0.592900  307.85333  0.748045    9  0.142496    -7.223   
55      0.425085      0.513255  123.64000  0.825107    5  0.721113    -9.180   
7       0.450516      0.687963   57.67791  0.925285    6  0.073633    -5.308   
6       0.126668      0.809788  228.16000  0.936480    9  0.217926    -6.633   
35      0.008030      0.633124  237.83995  0.960610    1  0.038698    -2.343   
37      0.028111      0.876175  231.26667  0.849825    5  0.107103    -6.551   
98      0.163220      0.695871  175.61601  0.651825    0  0.955150   -16.832   
55      0.000564      0.520229  211.06667  0.867121    2  0.118784    -6.345   
47      0.001883      0.890602  193.89333  0.602660    7  0.106475    -9.036   
49      0.977033      0.450264  249.61451  0.311056    4  0.176066    -8.175   
64      0.227755      0.637219  216.76000  0.859329    0  0.419714    -5.692   
29      0.282318      0.555122  288.62667  0.845501    0  0.206263    -6.388   
..           ...           ...        ...       ...  ...       ...       ...   
77      0.352961      0.747819  177.29333  0.792600    0  0.064876    -8.283   
1       0.482830      0.237851  279.38667  0.557238    2  0.112604    -8.147   
20      0.673924      0.528336  182.21333  0.270995    3  0.190486   -12.762   
46      0.298888      0.690010  228.43955  0.916487    7  0.381863    -6.229   
12      0.759930      0.428428  184.35039  0.454783   11  0.966722   -10.283   
78      0.027846      0.720983  147.43465  0.906277    8  0.097148    -8.165   
11      0.007620      0.819692  228.50712  0.651839    0  0.306439    -4.754   
40      0.390391      0.573884  198.80000  0.548441    8  0.101625    -8.120   
91      0.116844      0.651607  220.90667  0.966869    2  0.146750    -4.670   
96      0.080538      0.321896  284.35955  0.489506   10  0.053606    -8.755   
10      0.091430      0.609242  261.73624  0.616778   11  0.328686   -10.025   
25      0.027097      0.744023  215.76000  0.740782    1  0.092793    -4.981   
26      0.192178      0.470671  237.05556  0.386708   11  0.407869   -22.376   
62      0.319451      0.278800  265.73333  0.192506    0  0.118266   -15.939   
66      0.184189      0.625871  321.21333  0.659275    2  0.109635    -4.746   
82      0.070474      0.508482  404.02667  0.836394    5  0.966164    -9.444   
72      0.067219      0.702917  176.86667  0.832672    4  0.138708    -5.185   
16      0.185923      0.871374  197.88000  0.878531    0  0.159836    -6.514   
74  

In [46]:
# Splitting into test and training data
ys1_train, ys1_test, xs1_train, xs1_test = train_test_split(ys1, xs1, random_state=0)

In [47]:
model_s1tr = tree.DecisionTreeClassifier()
model_s1tr.fit(xs1_train, ys1_train) 
predicts_s1tr = model_s1tr.predict(xs1_test)

In [48]:
print(metrics.classification_report(predicts_s1tr, ys1_test))
print(metrics.accuracy_score(predicts_s1tr, ys1_test))     
print(metrics.confusion_matrix(predicts_s1tr, ys1_test))

             precision    recall  f1-score   support

        0.0       0.52      0.52      0.52        29
        1.0       0.36      0.36      0.36        22

avg / total       0.45      0.45      0.45        51

0.450980392157
[[15 14]
 [14  8]]


In [52]:
s1tr_fpr, s1_trtpr, thresholds = roc_curve(ys1_test, predicts_s1tr ,pos_label=1) 
s1tr_roc_auc = auc(s1tr_fpr, s1_trtpr)
s1tr_roc_auc


0.4404388714733542

In [ ]:
#Implemeting KNN

In [68]:
model_s1nn = KNeighborsClassifier(n_neighbors = 50)
model_s1nn.fit(xs1_train, ys1_train) 
predicts_s1nn = model_s1nn.predict(xs1_test )
metrics.accuracy_score(ys1_test, predicts_s1nn)

0.60784313725490191

In [70]:
metrics.confusion_matrix(ys1_test, predicts_s1nn)

array([[20,  9],
       [11, 11]])

In [71]:
s1nn_fpr, s1_nntpr, thresholds = roc_curve(ys1_test, predicts_s1nn ,pos_label=1) 
s1nn_roc_auc = auc(s1nn_fpr, s1_nntpr)
s1nn_roc_auc


0.59482758620689657

In [ ]:
# Building and analyzing Data Scenario 2

In [72]:
dhome = "/Users/avinesh/Google Drive/Courseworks/2 Sem/Python-based Data Analytics/Python Project/All Data/fsongs"
year = ['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2020']

# Adding label 1 to 2020 Dataset
filepath = dhome+year[10]+".csv"
s2df=pandas.read_csv(filepath)
grades = []
for row in s2df['ranks']:
    if  row <= 103:
        grades.append(1)
    else:
        grades.append(0)
s2df['grades'] = grades


In [73]:
s2df

ranks                              songs              artists  \
0        1                          THE TWIST       Chubby Checker   
1        2                             SMOOTH             santana    
2        3                     MACK THE KNIFE          Bobby Darin   
3        4                      HOW DO I LIVE          LeAnn Rimes   
4        5                  PARTY ROCK ANTHEM                lmfao   
5        6                    I GOTTA FEELING  The Black Eyed Peas   
6        7                          macarena           Los Del Rio   
7        8                           PHYSICAL   Olivia Newton-John   
8        9               YOU LIGHT UP MY LIFE          Debby Boone   
9       10                           HEY JUDE          The Beatles   
10      11                 WE BELONG TOGETHER         Mariah Carey   
11      12                       UPTOWN FUNK!         mark ronson    
12      13                  UN-BREAK MY HEART         Toni Braxton   
13      14                              YEAH!                usher   
14      15                   BETTE DAVIS EYES           Kim Carnes   
15      16                       ENDLESS LOVE          diana ross    
16      17               tonight's the night           Rod Stewart   
17      18                      FOOLISH GAMES                Jewel   
18      19              YOU WERE MEANT FOR ME                Jewel   
19      20  (EVERYTHING I DO) I DO IT FOR YOU          Bryan Adams   
20      21              I'LL MAKE LOVE TO YOU          Boyz II Men   
21      22    THE THEME FROM "A SUMMER PLACE"          Percy Faith   
22      23                           LE FREAK                 Chic   
23      24              HOW DEEP IS YOUR LOVE             Bee Gees   
24      25                   EYE OF THE TIGER             Survivor   
25      26                      WE FOUND LOVE             rihanna    
26      27                                LOW            flo rida    
27      28  I JUST WANT TO BE YOUR EVERYTHING            Andy Gibb   
28      29                          TOO CLOSE                 Next   
29      30              EVERY BREATH YOU TAKE           The Police   
..     ...                                ...                  ...   
72      73                           whoomp!              Tag Team   
73      74                  MOVES LIKE JAGGER            maroon 5    
74      75                    EBONY AND IVORY       Paul McCartney   
75      76                          RUSH RUSH          Paula Abdul   
76      77        THAT'S WHAT FRIENDS ARE FOR              dionne    
77      78                              HAPPY    Pharrell Williams   
78      79                        UPSIDE DOWN           Diana Ross   
79      80                       SUGAR, SUGAR          The Archies   
80      81               JUST THE WAY YOU ARE           Bruno Mars   
81      82                            DILEMMA               nelly    
82      83   I HEARD IT THROUGH THE GRAPEVINE          Marvin Gaye   
83      84               YOU'RE STILL THE ONE         Shania Twain   
84      85                        BILLIE JEAN      Michael Jackson   
85      86                          HOT STUFF         Donna Summer   
86      87                 GANGSTA'S PARADISE              coolio    
87      88                        ABRACADABRA    Steve Miller Band   
88      89                     YOU'RE SO VAIN          Carly Simon   
89      90              PLAY THAT FUNKY MUSIC          Wild Cherry   
90      91                    SAY YOU, SAY ME        Lionel Richie   
91      92                         MY SHARONA            The Knack   
92      93                    all night long         Lionel Richie   
93      94               NOTHING COMPARES 2 U      Sinead O'Connor   
94      95                            I SWEAR            All-4-One   
95      96                      FAMILY AFFAIR        Mary J. Blige   
96      97        WAITING FOR A GIRL LIKE YOU            Foreigner   
97      98     

In [74]:
# Adding label 0 to Remaining Dataset
for i in range(0,10):
    filepath = dhome+year[i]+".csv"
    mds = pandas.read_csv(filepath,header=0)
    grades = []
    for row in mds['ranks']:
        if  row <= 101:
            grades.append(0)
        else:
            grades.append(1)
    mds['grades'] = grades
    s2df = s2df.append(mds)

In [82]:
s2df['grades']
len(s2df['grades'][99])

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
     ..
70    0
71    0
72    0
73    0
74    0
75    0
76    0
77    0
78    0
79    0
80    0
81    0
82    0
83    0
84    0
85    0
86    0
87    0
88    0
89    0
90    0
91    0
92    0
93    0
94    0
95    0
96    0
97    0
98    0
99    0
Name: grades, dtype: int64

In [83]:
# Dropping Duplicates
s2od = s2df.sort(['songs','artists'], ascending=[1,0])
s2ot = s2od.drop_duplicates(['songs','artists'], keep='first')
s2ot.shape
s2ot.columns.values


C:\Users\avinesh\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app


array(['ranks', 'songs', 'artists', 'ids', 'acousticness', 'danceability',
       'duration', 'energy', 'key', 'liveness', 'loudness', 'mode',
       'speechiness', 'tempo', 'time_signature', 'valence', 'Anger',
       'Surprise', 'Joy', 'Sadness', 'Love', 'Fear', 'grades'], dtype=object)

In [84]:
# Splitting into dependent and independent varialbes 
ys2, xs2 = dmatrices('grades ~ acousticness + danceability + duration + energy + key + liveness + loudness + mode + speechiness + tempo + time_signature + valence + Anger + Surprise + Love + Joy + Sadness + Fear', 
                   data = s2ot, return_type="dataframe")
ys2 = numpy.ravel(ys2)

In [86]:
xs2.pop('Intercept')

19    1
65    1
96    1
60    1
64    1
77    1
77    1
70    1
89    1
86    1
22    1
85    1
80    1
40    1
20    1
91    1
55    1
42    1
50    1
86    1
87    1
54    1
96    1
99    1
96    1
46    1
31    1
5     1
32    1
70    1
     ..
6     1
31    1
80    1
38    1
81    1
16    1
79    1
40    1
13    1
73    1
69    1
6     1
39    1
46    1
12    1
55    1
96    1
7     1
90    1
6     1
55    1
78    1
36    1
57    1
15    1
16    1
77    1
78    1
72    1
43    1
Name: Intercept, dtype: float64

In [88]:
# Splitting intotraining and test data
ys2_train, ys2_test, xs2_train, xs2_test = train_test_split(ys2, xs2, random_state=0)

In [90]:
# Implementing trees
model_s2tr = tree.DecisionTreeClassifier()
model_s2tr.fit(xs2_train, ys2_train) 
predicts_s2tr = model_s2tr.predict(xs2_test)

In [91]:
print(metrics.classification_report(predicts_s2tr, ys2_test))
print(metrics.accuracy_score(ys2_test, predicts_s2tr ))     
print(metrics.confusion_matrix(ys2_test , predicts_s2tr))

             precision    recall  f1-score   support

        0.0       0.88      0.93      0.91       211
        1.0       0.42      0.27      0.33        37

avg / total       0.81      0.83      0.82       248

0.834677419355
[[197  27]
 [ 14  10]]


In [92]:
s2tr_fpr, s2_trtpr, thresholds = roc_curve(ys2_test, predicts_s2tr ,pos_label=1) 
s2tr_roc_auc = auc(s2tr_fpr, s2_trtpr)
s2tr_roc_auc


0.64806547619047616

In [ ]:
# Implementing KNN

In [93]:
model_s2nn = KNeighborsClassifier(n_neighbors = 50)
model_s2nn.fit(xs2_train, ys2_train) 
predicts_s2nn = model_s2nn.predict(xs2_test )
print(metrics.accuracy_score(ys2_test, predicts_s2nn))
print(metrics.confusion_matrix(ys2_test, predicts_s2nn))

0.903225806452
[[224   0]
 [ 24   0]]


In [94]:
s2nn_fpr, s2_nntpr, thresholds = roc_curve(ys2_test, predicts_s2nn ,pos_label=1) 
s2nn_roc_auc = auc(s2nn_fpr, s2_nntpr)
s2nn_roc_auc


0.5

In [ ]:
# Building and analyzing Data Scenario 3


In [25]:
# Adding label 0 to 2030 Dataset
year = ['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2030']
filepath = dhome+year[10]+".csv"
s3df=pd.read_csv(filepath)
grades = []
for row in s3df['ranks']:
    grades.append(0)
s3df['grades'] = grades



In [27]:
# Adding label 1 to the top 20 songs from 2006 to 2015


dhome = "/Users/avinesh/Google Drive/Courseworks/2 Sem/Python-based Data Analytics/Python Project/All Data/fsongs"
year = ['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2030']


for i in range(0,10):
    filepath = dhome+year[i]+".csv"
    tempdf1 = pandas.read_csv(filepath,header=0)
    grades = []
    for row in tempdf1['ranks']:
        if  row <= 20:
            grades.append(1)
        else:
            grades.append(0)
    tempdf1['grades'] = grades
    s3df = s3df.append(tempdf1)

In [28]:
print(s3df.shape)

19    0
19    1
19    1
19    1
19    1
19    1
19    1
19    1
19    1
19    1
19    1
Name: grades, dtype: int64
11
(1100, 23)


In [29]:
# Dropping Duplicates
s3od = s3df.sort(['songs','artists'], ascending=[1,0])
s3ot = s3od.drop_duplicates(['songs','artists'], keep='first')
print(s3ot.shape)
print(s3ot.columns.values)


(1009, 23)
['ranks' 'songs' 'artists' 'ids' 'acousticness' 'danceability' 'duration'
 'energy' 'key' 'liveness' 'loudness' 'mode' 'speechiness' 'tempo'
 'time_signature' 'valence' 'Anger' 'Surprise' 'Joy' 'Sadness' 'Love'
 'Fear' 'grades']


C:\Users\avinesh\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app


In [30]:
# Splitting into dependent and independent variables
ys3, xs3 = dmatrices('grades ~ acousticness + danceability + duration + energy + key + liveness + loudness + mode + speechiness + tempo + time_signature + valence + Anger + Surprise + Love + Joy + Sadness + Fear', 
                   data = s3ot, return_type="dataframe")
ys3 = numpy.ravel(ys3)

In [31]:
xs3.pop('Intercept')

13    1
96    1
60    1
64    1
77    1
77    1
70    1
89    1
86    1
22    1
85    1
17    1
80    1
40    1
20    1
91    1
55    1
42    1
50    1
86    1
54    1
96    1
99    1
96    1
46    1
31    1
5     1
32    1
7     1
68    1
     ..
95    1
48    1
99    1
6     1
31    1
80    1
38    1
81    1
16    1
79    1
40    1
13    1
73    1
69    1
39    1
46    1
12    1
55    1
96    1
7     1
90    1
6     1
55    1
78    1
36    1
57    1
15    1
77    1
78    1
43    1
Name: Intercept, dtype: float64

In [32]:
xs3.columns.values

array(['acousticness', 'danceability', 'duration', 'energy', 'key',
       'liveness', 'loudness', 'mode', 'speechiness', 'tempo',
       'time_signature', 'valence', 'Anger', 'Surprise', 'Love', 'Joy',
       'Sadness', 'Fear'], dtype=object)

In [33]:
# Splitting into test and training data
ys3_train, ys3_test, xs3_train, xs3_test = train_test_split(ys3, xs3, random_state=0)

In [34]:
# Implementing logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
model_lrs3 = LogisticRegression()
model_lrs3.fit(xs3_train, ys3_train)  

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [35]:
model_lrs3.coef_

array([[ -3.97091269e-02,   1.33863240e+00,  -1.15945165e-03,
         -8.67564450e-01,   3.47791559e-02,   6.67221676e-01,
         -1.72543146e-02,  -3.13527475e-01,  -9.58252862e-01,
         -3.07872240e-04,  -4.99918524e-02,   5.43439870e-01,
         -1.15588011e-01,   1.72058063e-01,  -1.40505379e-01,
         -1.74636377e-01,  -8.24457035e-02,  -1.73964713e-01]])

In [36]:
xs3_train.columns.values

array(['acousticness', 'danceability', 'duration', 'energy', 'key',
       'liveness', 'loudness', 'mode', 'speechiness', 'tempo',
       'time_signature', 'valence', 'Anger', 'Surprise', 'Love', 'Joy',
       'Sadness', 'Fear'], dtype=object)

In [114]:
# Implementing trees
model_s3tr = tree.DecisionTreeClassifier()
model_s3tr.fit(xs3_train, ys3_train) 
predicts_s3tr = model_s3tr.predict(xs3_test)

In [115]:
print(metrics.classification_report(predicts_s3tr, ys3_test))
print(metrics.accuracy_score(ys3_test, predicts_s3tr ))     
print(metrics.confusion_matrix(ys3_test , predicts_s3tr))

             precision    recall  f1-score   support

        0.0       0.79      0.81      0.80       199
        1.0       0.24      0.22      0.23        54

avg / total       0.68      0.68      0.68       253

0.683794466403
[[161  42]
 [ 38  12]]


In [116]:
s3tr_fpr, s3_trtpr, thresholds = roc_curve(ys3_test, predicts_s3tr ,pos_label=1) 
s3tr_roc_auc = auc(s3tr_fpr, s3_trtpr)
s3tr_roc_auc


0.51655172413793105

In [123]:
# Implementing K Nearest Neighbors
model_s3nn = KNeighborsClassifier(n_neighbors = 10)
model_s3nn.fit(xs3_train, ys3_train) 
predicts_s3nn = model_s3nn.predict(xs3_test )
print(metrics.accuracy_score(ys3_test, predicts_s3nn))
print(metrics.confusion_matrix(ys3_test, predicts_s3nn))

0.802371541502
[[203   0]
 [ 50   0]]


In [125]:
s3nn_fpr, s3_nntpr, thresholds = roc_curve(ys3_test, predicts_s3nn ,pos_label=1) 
s3nn_roc_auc = auc(s3nn_fpr, s3_nntpr)
s3nn_roc_auc


0.5

In [ ]:
# Building and analyzing Data Scenario 4

In [126]:
dhome = "/Users/avinesh/Google Drive/Courseworks/2 Sem/Python-based Data Analytics/Python Project/All Data/fsongs"
year = ['2030','2020','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']
# Adding label 1 to 2020 Dataset
filepath = dhome+year[1]+".csv"
df=pd.read_csv(filepath)
grades = []


In [133]:
df

ranks                              songs               artists  \
0       1                          THE TWIST        Chubby Checker   
1       2                             SMOOTH              santana    
2       3                     MACK THE KNIFE           Bobby Darin   
3       4                      HOW DO I LIVE           LeAnn Rimes   
4       5                  PARTY ROCK ANTHEM                 lmfao   
5       6                    I GOTTA FEELING   The Black Eyed Peas   
6       7                          macarena            Los Del Rio   
7       8                           PHYSICAL    Olivia Newton-John   
8       9               YOU LIGHT UP MY LIFE           Debby Boone   
9      10                           HEY JUDE           The Beatles   
10     11                 WE BELONG TOGETHER          Mariah Carey   
11     12                       UPTOWN FUNK!          mark ronson    
12     13                  UN-BREAK MY HEART          Toni Braxton   
13     14                              YEAH!                 usher   
14     15                   BETTE DAVIS EYES            Kim Carnes   
15     16                       ENDLESS LOVE           diana ross    
16     17               tonight's the night            Rod Stewart   
17     18                      FOOLISH GAMES                 Jewel   
18     19              YOU WERE MEANT FOR ME                 Jewel   
19     20  (EVERYTHING I DO) I DO IT FOR YOU           Bryan Adams   
20     21              I'LL MAKE LOVE TO YOU           Boyz II Men   
21     22    THE THEME FROM "A SUMMER PLACE"           Percy Faith   
22     23                           LE FREAK                  Chic   
23     24              HOW DEEP IS YOUR LOVE              Bee Gees   
24     25                   EYE OF THE TIGER              Survivor   
25     26                      WE FOUND LOVE              rihanna    
26     27                                LOW             flo rida    
27     28  I JUST WANT TO BE YOUR EVERYTHING             Andy Gibb   
28     29                          TOO CLOSE                  Next   
29     30              EVERY BREATH YOU TAKE            The Police   
..    ...                                ...                   ...   
97     98                    FLY OVER STATES          Jason Aldean   
98     99       EVEN IF IT BREAKS YOUR HEART        Eli Young Band   
99    100                       BURN IT DOWN           Linkin Park   
91     92                             WANTED          Hunter Hayes   
92     93                           DOWNTOWN       Lady Antebellum   
93     94                  GET YOUR SHINE ON  Florida Georgia Line   
94     95                          THATPOWER            will.i.am    
95     96                              BRAVE        Sara Bareilles   
96     97                         LET HER GO             Passenger   
97     98            RUNNIN' OUTTA MOONLIGHT          Randy Houser   
98     99                      I'M DIFFERENT              2 Chainz   
99    100                     STILL INTO YOU              Paramore   
91     92                        WHITE WALLS            macklemore   
92     93               SHE LOOKS SO PERFECT   5 Seconds Of Summer   
93     94                     STAY THE NIGHT                 zedd    
94     95                          PARTITION               Beyonce   
95     96                             STUDIO          schoolboy q    
96     97            0 TO 100 / THE CATCH UP                 Drake   
97     98                      I DON'T DANCE             Lee Brice   
98     99                      SOMETHIN' BAD       miranda lambert   
99    100                          ADORE YOU           Miley Cyrus   
91     92                              DON'T            Ed Sheeran   
92     93                              GHOST        Ella Henderson   
93     94                               HERE          Alessia Cara   
94     95                              WAVES             Mr. Probz   
95     96     

In [128]:
for row in df['ranks']:
    grades.append(1)
    
df['grades'] = grades


In [130]:

#Adding label 0 to 2030 Dataset
filepath = dhome+year[0]+".csv"
df1=pd.read_csv(filepath)
grades = []
for row in df1['ranks']:
    grades.append(0)

df1['grades'] = grades

df = df.append(df1)



In [132]:

# Adding label 0 to Remaining Dataset
for i in range(2,12):
    filepath = dhome+year[i]+".csv"
    mds = pd.read_csv(filepath,header=0)
    grades = []
    for row in mds['ranks']:
        if  row > 90:
            grades.append(1)
        else:
            grades.append(0)
    mds['grades'] = grades
    df = df.append(mds[91:])


In [134]:


print(list(df.columns.values))


['ranks', 'songs', 'artists', 'ids', 'acousticness', 'danceability', 'duration', 'energy', 'key', 'liveness', 'loudness', 'mode', 'speechiness', 'tempo', 'time_signature', 'valence', 'Anger', 'Surprise', 'Joy', 'Sadness', 'Love', 'Fear', 'grades']


In [149]:
# Dropping Duplicates
s4od = df.sort(['songs','artists'], ascending=[1,0])
s4ot = s4od.drop_duplicates(['songs','artists'], keep='first')
print(s4ot.shape)
print(s4ot.columns.values)


(292, 23)
['ranks' 'songs' 'artists' 'ids' 'acousticness' 'danceability' 'duration'
 'energy' 'key' 'liveness' 'loudness' 'mode' 'speechiness' 'tempo'
 'time_signature' 'valence' 'Anger' 'Surprise' 'Joy' 'Sadness' 'Love'
 'Fear' 'grades']


C:\Users\avinesh\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app


In [150]:
# Splitting into dependent and independent variables
ys4, xs4 = dmatrices('grades ~ -1 + acousticness + danceability + duration + energy + key + liveness + loudness + mode + speechiness + tempo + time_signature + valence + Anger + Surprise + Love + Joy + Sadness + Fear', 
                   data = s4ot, return_type="dataframe")
ys4 = numpy.ravel(ys4)

In [151]:
xs4

acousticness  danceability   duration    energy  key  liveness  loudness  \
19      0.074356      0.517933  393.60000  0.492540    1  0.069184    -7.396   
13      0.074356      0.517933  393.60000  0.492540    1  0.069184    -7.396   
65      0.473817      0.511773  242.36000  0.823738    9  0.080829    -7.269   
96      0.656259      0.655754  274.12000  0.584733   11  0.576725    -8.176   
17      0.004035      0.682043  201.77333  0.987871    2  0.283666    -3.859   
91      0.024306      0.600530  216.49333  0.880661    1  0.064578    -4.892   
87      0.007207      0.784116  306.29288  0.664036    9  0.158843    -8.482   
96      0.000327      0.501678  225.73333  0.846119    0  0.083094    -4.885   
99      0.053297      0.549344  245.91125  0.577499    0  0.210349    -7.984   
96      0.137173      0.559591  196.10667  0.603488    2  0.113865    -5.208   
70      0.068485      0.806061  188.02667  0.855451    9  0.116679    -5.313   
94      0.216564      0.208044  281.28000  0.871984    9  0.077050    -2.996   
93      0.528618      0.583497  224.96757  0.663079    1  0.113765    -5.941   
96      0.006470      0.523026  211.02621  0.911897    5  0.271509    -5.402   
40      0.096857      0.927517  215.33333  0.530833    5  0.160141    -6.520   
62      0.038555      0.657365  184.61333  0.558068    8  0.091263    -7.474   
71      0.165766      0.164260  287.37333  0.724350    7  0.046118    -5.699   
95      0.043888      0.485361  182.88000  0.661898    8  0.094525    -4.771   
97      0.970227      0.309855   25.05098  0.037436    9  0.111845   -17.672   
8       0.157461      0.772159  196.31020  0.847969    4  0.129609    -9.084   
2       0.205136      0.840790  188.08000  0.836344    4  0.112933    -9.618   
15      0.682217      0.517781  204.04000  0.457250   10  0.105137    -5.470   
80      0.348156      0.631360  273.53333  0.734136    5  0.134955    -7.480   
19      0.283630      0.672349  212.28798  0.709183    1  0.082996    -7.884   
98      0.008983      0.634696  170.63778  0.471954    8  0.116628    -3.869   
14      0.024585      0.746524  243.28000  0.866535    5  0.154258    -8.525   
96      0.190778      0.444017  223.48000  0.686303    2  0.152866    -5.199   
84      0.622172      0.423947  216.58331  0.236798    6  0.095008   -13.035   
48      0.003475      0.862859  263.82667  0.611065    7  0.085732    -4.775   
54      0.140373      0.592900  307.85333  0.748045    9  0.142496    -7.223   
..           ...           ...        ...       ...  ...       ...       ...   
94      0.024641      0.807292  179.84000  0.548106    1  0.130482    -8.649   
10      0.091430      0.609242  261.73624  0.616778   11  0.328686   -10.025   
25      0.027097      0.744023  215.76000  0.740782    1  0.092793    -4.981   
93      0.443022      0.686293  208.21333  0.575644    1  0.212022    -6.632   
93      0.337358      0.648808  225.21333  0.480734    6  0.158796    -9.726   
91      0.054118      0.767477  220.31946  0.781970    7  0.337897    -5.545   
94      0.363466      0.797878  216.19955  0.698942    1  0.057160    -5.545   
26      0.192178      0.470671  237.05556  0.386708   11  0.407869   -22.376   
62      0.319451      0.278800  265.73333  0.192506    0  0.118266   -15.939   
66      0.184189      0.625871  321.21333  0.659275    2  0.109635    -4.746   
82      0.070474      0.508482  404.02667  0.836394    5  0.966164    -9.444   
72      0.067219      0.702917  176.86667  0.832672    4  0.138708    -5.185   
16      0.185923      0.871374  197.88000  0.878531    0  0.159836    -6.514   
74      0.550727      0.509541  293.85306  0.457868   10  0.085258    -7.566   
39      0.631826      0.696586  206.11955  0.662929    9  0.190943    -8.718   
13      0.026457      0.845517  174.48000  0.570809    5  0.039566   -10.197   
97      0.801814      0.457001  662.43156  0.323539    6  0.606749   -20.716   
8       0.855203      0.322341  218.93333  0.282051    2  0.162640   -12.516   
18  

In [152]:
# Splitting into test and training data 
ys4_train, ys4_test, xs4_train, xs4_test = train_test_split(ys4, xs4, random_state=0)

In [153]:
# Implementing trees
model_s4tr = tree.DecisionTreeClassifier()
model_s4tr.fit(xs4_train, ys4_train) 
predicts_s4tr = model_s4tr.predict(xs4_test)

In [154]:
print(metrics.classification_report(predicts_s4tr, ys4_test))
print(metrics.accuracy_score(ys4_test, predicts_s4tr ))     
print(metrics.confusion_matrix(ys4_test , predicts_s4tr))

             precision    recall  f1-score   support

        0.0       0.58      0.44      0.50        34
        1.0       0.60      0.72      0.65        39

avg / total       0.59      0.59      0.58        73

0.58904109589
[[15 11]
 [19 28]]


In [155]:
s4tr_fpr, s4_trtpr, thresholds = roc_curve(ys4_test, predicts_s4tr ,pos_label=1) 
s4tr_roc_auc = auc(s4tr_fpr, s4_trtpr)
s4tr_roc_auc


0.58633387888707034

In [156]:
# Implementing NN
model_s4nn = KNeighborsClassifier(n_neighbors = 50)
model_s4nn.fit(xs4_train, ys4_train) 
predicts_s4nn = model_s4nn.predict(xs4_test )
print(metrics.accuracy_score(ys4_test, predicts_s4nn))
print(metrics.confusion_matrix(ys4_test, predicts_s4nn))

0.643835616438
[[ 0 26]
 [ 0 47]]


In [157]:
s4nn_fpr, s4nn_tpr, thresholds = roc_curve(ys4_test, predicts_s4nn ,pos_label=1) 
s4nn_roc_auc = auc(s4nn_fpr, s4nn_tpr)
s4nn_roc_auc


0.5

In [ ]:
# Building and analyzing Data Scenario 5


In [159]:
dhome = "/Users/avinesh/Google Drive/Courseworks/2 Sem/Python-based Data Analytics/Python Project/All Data/fsongs"
year = ['2030','2020','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']
# Creating an empty dataframe 
df = pd.DataFrame()
grades = []


In [161]:

# Adding label 0 to Remaining Dataset
for i in range(2,12):
    filepath = dhome+year[i]+".csv"
    mds = pd.read_csv(filepath, header=0)
    grades = []
    for row in mds['ranks']:
        if  row < 20:
            grades.append(1)
        else:
            grades.append(0)
    mds['grades'] = grades
    df = df.append(mds)


In [162]:
df

ranks                       songs                   artists  \
0       1                     BAD DAY             Daniel Powter   
1       2                 TEMPERATURE                 Sean Paul   
2       3                 PROMISCUOUS            nelly furtado    
3       4            YOU'RE BEAUTIFUL               James Blunt   
4       5              HIPS DON'T LIE                  shakira    
5       6                   UNWRITTEN       Natasha Bedingfield   
6       7                       CRAZY            Gnarls Barkley   
7       8                      RIDIN'           chamillionaire    
8       9                    SEXYBACK         Justin Timberlake   
9      10                 CHECK ON IT                  beyonce    
10     11              BE WITHOUT YOU             Mary J. Blige   
11     12                      GRILLZ                    nelly    
12     13               over my head                   The Fray   
13     14                    ME and U                    Cassie   
14     15                     BUTTONS       the pussycat dolls    
15     16                     RUN IT!               Chris Brown   
16     17                     SO SICK                     Ne-Yo   
17     18             IT'S GOIN' DOWN                  Yung Joc   
18     19                         SOS                   Rihanna   
19     20  I WRITE SINS NOT TRAGEDIES       Panic! At The Disco   
20     21                  MOVE ALONG  The All-American Rejects   
21     22               LONDON BRIDGE                    Fergie   
22     23             DANI CALIFORNIA     Red Hot Chili Peppers   
23     24             SNAP YO FINGERS                  lil jon    
24     25    LEAN WIT IT, ROCK WIT IT       dem franchize boyz    
25     26         WHAT HURTS THE MOST             Rascal Flatts   
26     27          HOW TO SAVE A LIFE                  The Fray   
27     28                  UNFAITHFUL                   Rihanna   
28     29                CHASING CARS               Snow Patrol   
29     30            LIPS OF AN ANGEL                    Hinder   
..    ...                         ...                       ...   
70     71                     RIPTIDE                 Vance Joy   
71     72                 CLASSIC MAN                  jidenna    
72     73                   EX'S OH'S                 Elle King   
73     74         DEAR FUTURE HUSBAND            Meghan Trainor   
74     75                 MARVIN GAYE             charlie puth    
75     76     LIKE I'M GONNA LOSE YOU           meghan trainor    
76     77                     habits                    Tove Lo   
77     78            THE HANGING TREE      james newton howard    
78     79                        COCO              O.T. Genasis   
79     80                   BANG BANG                  Jessie J   
80     81                 LAY ME DOWN                 Sam Smith   
81     82                     TUESDAY          i love makonnen    
82     83                HIT THE QUAN              iLoveMemphis   
83     84                    DOWNTOWN                macklemore   
84     85                 HOUSE PARTY                  Sam Hunt   
85     86                         AYO              Chris Brown    
86     87            KICK THE DUST UP                Luke Bryan   
87     88                   BLESSINGS                 big sean    
88     89                    BUDAPEST               George Ezra   
89     90                  CHANDELIER                       Sia   
90     91              HEARTBEAT SONG            Kelly Clarkson   
91     92                       DON'T                Ed Sheeran   
92     93                       GHOST            Ella Henderson   
93     94                        HERE              Alessia Cara   
94     95                       WAVES                 Mr. Probz   
95     96                  el perdon                  Nicky Jam   
96     97                   SHE KNOWS                    ne-yo    
97     98               NIGHT CHANGES             O

In [163]:
# Dropping Duplicates
s5od = df.sort(['songs','artists'], ascending=[1,0])
s5ot = s5od.drop_duplicates(['songs','artists'], keep='first')
print(s5ot.shape)
print(s5ot.columns.values)

(909, 23)
['ranks' 'songs' 'artists' 'ids' 'acousticness' 'danceability' 'duration'
 'energy' 'key' 'liveness' 'loudness' 'mode' 'speechiness' 'tempo'
 'time_signature' 'valence' 'Anger' 'Surprise' 'Joy' 'Sadness' 'Love'
 'Fear' 'grades']


C:\Users\avinesh\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app


In [164]:
# Splitting into dependent and independent variables
ys5, xs5 = dmatrices('grades ~ -1 + acousticness + danceability + duration + energy + key + liveness + loudness + mode + speechiness + tempo + time_signature + valence + Anger + Surprise + Love + Joy + Sadness + Fear', 
                   data = s4ot, return_type="dataframe")
ys5 = numpy.ravel(ys5)

In [166]:
# Splitting into test and training data
ys5_train, ys5_test, xs5_train, xs5_test = train_test_split(ys5, xs5, random_state=0)

In [167]:
# Implementing trees
model_s5tr = tree.DecisionTreeClassifier()
model_s5tr.fit(xs5_train, ys5_train) 
predicts_s5tr = model_s5tr.predict(xs5_test)

In [168]:
print(metrics.classification_report(predicts_s5tr, ys5_test))
print(metrics.accuracy_score(ys5_test, predicts_s5tr ))     
print(metrics.confusion_matrix(ys5_test , predicts_s5tr))

             precision    recall  f1-score   support

        0.0       0.54      0.42      0.47        33
        1.0       0.60      0.70      0.64        40

avg / total       0.57      0.58      0.57        73

0.575342465753
[[14 12]
 [19 28]]


In [169]:
s5tr_fpr, s5_trtpr, thresholds = roc_curve(ys5_test, predicts_s5tr ,pos_label=1) 
s5tr_roc_auc = auc(s5tr_fpr, s5_trtpr)
s5tr_roc_auc


0.56710310965630106

In [170]:
# Implementing K Nearest Neighbors
model_s5nn = KNeighborsClassifier(n_neighbors = 50)
model_s5nn.fit(xs5_train, ys5_train) 
predicts_s5nn = model_s5nn.predict(xs5_test )
print(metrics.accuracy_score(ys5_test, predicts_s5nn))
print(metrics.confusion_matrix(ys5_test, predicts_s5nn))

0.643835616438
[[ 0 26]
 [ 0 47]]


In [171]:
s5nn_fpr, s5nn_tpr, thresholds = roc_curve(ys5_test, predicts_s5nn ,pos_label=1) 
s5nn_roc_auc = auc(s5nn_fpr, s5nn_tpr)
s5nn_roc_auc


0.5